# Cloudflare Tunnel configuration to preserve authentication headers
tunnel: your-tunnel-id
credentials-file: /path/to/credentials.json

ingress:
  - hostname: gensg-fastapi.tanfamily.cc
    service: http://192.168.1.160:8000
    originRequest:
      # Preserve all headers including Authorization
      noTLSVerify: true
      # Don't strip headers
      httpHostHeader: gensg-fastapi.tanfamily.cc
      # Preserve authentication headers
      originServerName: gensg-fastapi.tanfamily.cc
  - hostname: gensg.tanfamily.cc  
    service: http://192.168.1.160:3000
  - service: http_status:404