# Staging Environment: Containerized Frontend + Containerized Backend + Local PostgreSQL
# This setup allows testing both containers with your existing local test data

services:
  # FastAPI Backend (Containerized)
  backend:
    image: ghcr.io/joshzacharytan/generation-capstone-backend:latest
    container_name: ecommerce_backend_staging
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@host.docker.internal/ecommerce_db}
      - SECRET_KEY=${SECRET_KEY:-thisisatestingkey}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - ENVIRONMENT=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN:-gen-capstone.tanfamily.cc}
    volumes:
      - ./app/static/uploads:/app/static/uploads  # Persist uploaded files
    networks:
      - staging_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Production-ready React Frontend with NGINX (Containerized)
  frontend:
    image: ghcr.io/joshzacharytan/generation-capstone-frontend:latest
    container_name: ecommerce_frontend_staging
    restart: unless-stopped
    ports:
      - "80:80"     # Standard web port
      - "3000:80"   # Alternative access port
    environment:
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN:-gen-capstone.tanfamily.cc}
      # REACT_APP_API_BASE_URL intentionally not set to force relative /api paths through NGINX proxy
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - staging_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

# Persistent volumes for staging data
volumes:
  staging_uploads:
    driver: local

# Custom network for staging
networks:
  staging_network:
    driver: bridge